let sanpham =
    [
        {
            'id': 'lap1',
            'name': 'Dell Gaming7559 (Core i5-6300HQ, RAM 8GB, HDD 500GB + SSD 128GB, VGA 4GB GTX 960M, 15.6 inch FHD) Mới 98 >99%',
            'image': 'https://laptopaz.vn/media/product/849_laptop_dell_7559_laptopaz__7_.JPG',
            'price': 10 * Math.pow(10, 6),
            'cpu': 'i5 6300HQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'NVIDIA GTX 960M',
            'screen': 'FHD TN',
            "type": 'gaming',
        },
        {
            'id': 'lap2',
            'name': 'Laptop MSI GF63-9RC-273VN ',
            'image': 'https://laptopaz.vn/media/product/1346_laptop_msi_gf63_9rc_laptopaz__3_.JPG',
            'price': 17 * Math.pow(10, 6),
            'cpu': 'i5 6300HQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'NVIDIA GTX 960M',
            'screen': 'FHD TN',
            "type": 'gaming',
        },
        {
            'id': 'lap3',
            'name': 'Dell G7 7588 ',
            'image': 'https://laptopaz.vn/media/product/1172_dell_inspiron_g7_7588_laptopaz__4_.JPG',
            'price': 17 * Math.pow(10, 6),
            'cpu': 'i5 6300HQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'NVIDIA GTX 960M',
            'screen': 'FHD TN',
            "type": 'gaming',
        },
        {
            'id': 'lap5',
            'name': 'Dell G7 7588 ',
            'image': 'https://laptopaz.vn/media/product/1172_dell_inspiron_g7_7588_laptopaz__4_.JPG',
            'price': 17 * Math.pow(10, 6),
            'cpu': 'i5 6300HQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'NVIDIA GTX 960M',
            'screen': 'FHD TN',
            "type": 'gaming',
        },
        {
            'id': 'lap5',
            'name': 'Dell G7 7588 ',
            'image': 'https://laptopaz.vn/media/product/1172_dell_inspiron_g7_7588_laptopaz__4_.JPG',
            'price': 17 * Math.pow(10, 6),
            'cpu': 'i5 6300HQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'NVIDIA GTX 960M',
            'screen': 'FHD TN',
            "type": 'gaming',

        },
        {
            'id': 'lap1',
            'name': 'Laptop HP EliteBook 840 G3 (Core i5-6200U, RAM 8GB, SSD 256GB, VGA Intel HD Graphics 520, 14 inch FHD)',
            'image': 'https://laptopaz.vn/media/product/1144_laptop_hp_840_g3_laptopaz__11_.JPG',
            'price': 9 * Math.pow(10, 6),
            'cpu': 'Core i5 6200U',
            'ram': '8GB',
            'hrdw': 'SSD 256GB',
            'vga': 'Intel UHD Graphics 520',
            'screen': 'FHD IPS',
            "type": 'thin',
        },
        {
            'id': 'lap2',
            'name': 'Laptop HP ENVY 13 ah0026TU (Core i5-8250U, RAM 8GB, SSD 256GB, VGA Intel UHD Graphics 620, 13.3 inch FHD + IPS) ',
            'image': 'https://laptopaz.vn/media/product/1173_img_0966.JPG',
            'price': 24 * Math.pow(10, 6),
            'cpu': 'i5 6300HQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'NVIDIA GTX 960M',
            'screen': 'FHD TN',
            "type": 'thin',
        },
        {
            'id': 'lap3',
            'name': 'Laptop Dell XPS 13-9350 (Core i7-6500U, RAM 8GB, SSD 256GB, VGA Intel HD Grapics 520, 13.3 inch FH IPS) ',
            'image': 'https://laptopaz.vn/media/product/858_laptop_dell_xps_9350_laptopa__7_.JPG',
            'price': 18 * Math.pow(10, 6),
            'cpu': 'i5 6300HQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'NVIDIA GTX 960M',
            'screen': 'FHD TN',
            "type": 'thin',
        },
        {
            'id': 'lap5',
            'name': 'Dell G7 7588 ',
            'image': 'https://laptopaz.vn/media/product/1172_dell_inspiron_g7_7588_laptopaz__4_.JPG',
            'price': 17 * Math.pow(10, 6),
            'cpu': 'i5 6300HQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'NVIDIA GTX 960M',
            'screen': 'FHD TN',
            "type": 'thin',
        },
        {
            'id': 'lap5',
            'name': 'Laptop HP EliteBook 840 G2 (Core i5-5300U, RAM 4GB, SSD 128GB, VGA Intel HD Graphics 4400, 14 inch) ',
            'image': 'https://laptopaz.vn/media/product/1254_laptop_hp_840_g2_laptopaz__11_.JPG',
            'price': 8 * Math.pow(10, 6),
            'cpu': 'i5 5300U',
            'ram': '4GB',
            'hrdw': 'SSD 128GB',
            'vga': 'Intel HD Graphics 4400',
            'screen': '14 Inch',
            "type": 'thin',
        },
        {
            'id': 'lap1',
            'name': 'Laptop Lenovo Y520 15IKBN (Core i5-7300HQ, RAM 8GB, HDD 1TB + SSD 128GB M2, VGA 4GB NVIDIA GTX 1050, 15.6 inch, Full HD IPS)',
            'image': 'https://laptopaz.vn/media/product/1047_laptop_lenovo_y520_laptopaz__7_.JPG',
            'price': 14 * Math.pow(10, 6),
            'cpu': 'Core i5-7300HQ',
            'ram': '8GB',
            'hrdw': 'HDD 1TB + SSD 128GB',
            'vga': 'NVIDIA GTX 1050 4GB',
            'screen': '15.6 FHD IPS',
            "type": 'lenovo',
        },
        {
            'id': 'lap2',
            'name': 'Laptop Lenovo Thinkpad T470 (Core i5-7300U, RAM 8GB, SSD 256GB, VGA Intel UHD Graphics 620, 14 inch FHD + IPS)',
            'image': 'https://laptopaz.vn/media/product/1421_1288_laptop_lenovo_thinkpad_t450s_laptopaz__1_.jpg',
            'price': 15 * Math.pow(10, 6),
            'cpu': 'Core i5-7300U',
            'ram': '8GB',
            'hrdw': 'SSD 256GB',
            'vga': 'Intel HD Graphics 620',
            'screen': '14 FHD IPS',
            "type": 'lenovo',
        },
        {
            'id': 'lap3',
            'name': 'Lenovo Ideadpad L340 15IRH mới 100% (Core i5-9300H, RAM 8GB, HDD 1TB, VGA 3GB NVIDIA GTX 1050, 15.6 inch, FHD IPS)',
            'image': 'https://laptopaz.vn/media/product/1352_lenovo_l340_laptopaz__5_.JPG',
            'price': 16 * Math.pow(10, 6),
            'cpu': 'Core i7 9750H',
            'ram': '8GB',
            'hrdw': 'SSD 512GB',
            'vga': 'NVIDIA GTX 1660Ti',
            'screen': '15.6 FHD IPS 144Hz',
            "type": 'lenovo',
        },
        {
            'id': 'lap4',
            'name': 'Laptop Lenovo Legion Y540-15IRH Core i5 9th BH chính hãng đến 7/2020',
            'image': 'https://laptopaz.vn/media/product/1363_acer_predator_helios_300__3_.JPG',
            'price': 33 * Math.pow(10, 6),
            'cpu': 'Core i5 9300H',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 1TB',
            'vga': 'NVIDIA GTX 1650 4GB',
            'screen': '15.6 icnh FHD',
            "type": 'lenovo',
        },
        {
            'id': 'lap5',
            'name': 'Laptop Lenovo Thinkpad X1 Carbon Gen 4 (Core i5-6200U, RAM 8GB, SSD 256GB, VGA intel HD Graphics 520, 14 inch FHD)',
            'image': 'https://laptopaz.vn/media/product/1172_dell_inspiron_g7_7588_laptopaz__4_.JPG',
            'price': 15 * Math.pow(10, 6),
            'cpu': 'https://laptopaz.vn/media/product/1335_laptop_lenovo_thinkpad_x1_carbon_gen_4_laptopaz__8_.JPEG',
            'ram': '8GB',
            'hrdw': 'SSD 256GB',
            'vga': 'Intell UHD Graphics 520',
            'screen': 'FHD IPS',
            "type": 'lenovo',
        },
        {
            'id': 'lap1',
            'name': 'Laptop Razer Blade 15 2018 (Core i7-8750H, RAM 16GB, SSD 512GB, VGA 6GB NVIDIA GTX 1060, 15.6 inch FHD IPS) Mới 99%',
            'image': 'https://laptopaz.vn/media/product/1334_laptop_razer_blade_15_2018_laptopaz__8_.JPEG',
            'price': 33 * Math.pow(10, 6),
            'cpu': 'Core i7 8750H',
            'ram': '16GB',
            'hrdw': 'SSD 512GB',
            'vga': 'NDIVIA GTX 1060 6GB',
            'screen': 'FHD',
            "type": "new",
        },
        {
            'id': 'lap2',
            'name': 'Laptop HP Pavilion 15 CX0056 (Core i5-8300H, RAM 8GB, HDD 1TB, VGA 4Gb NVDIA GTX 1050Ti, 15.6 inch FHD IPS) ',
            'image': 'https://laptopaz.vn/media/product/1261_laptop_hp_pavilion_15_i5_laptopaz__7_.JPG',
            'price': 18 * Math.pow(10, 6),
            'cpu': 'i5 6300HQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'NVIDIA GTX 960M',
            'screen': 'FHD TN',
            "type": "new",
        },
        {
            'id': 'lap3',
            'name': 'Laptop MSI Gaming GL73 cũ 99%',
            'image': 'https://laptopaz.vn/media/product/1172_dell_inspiron_g7_7588_laptopaz__4_.JPG',
            'price': 18 * Math.pow(10, 6),
            'cpu': 'i5 6300HQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'NVIDIA GTX 960M',
            'screen': 'FHD TN',
            "type": "new",
        },
        {
            'id': 'lap4',
            'name': 'Laptop Dell Gaming G5 5590 mới 100%',
            'image': 'https://laptopaz.vn/media/product/1427_g5_5590_1_1.jpg',
            'price': 25 * Math.pow(10, 6),
            'cpu': 'i5 6300HQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'NVIDIA GTX 960M',
            'screen': 'FHD TN',
            "type": "new",
        },
        {
            'id': 'lap5',
            'name': 'Acer Predator Helios 300 (Core i7-9750H, RAM 16GB,SSD 512GB, VGA 6GB NVIDIA GTX 1660Ti, 15.6 inch FHD IPS+144Hz) mới 100% nhập US ',
            'image': 'https://laptopaz.vn/media/product/1172_dell_inspiron_g7_7588_laptopaz__4_.JPG',
            'price': 33 * Math.pow(10, 6),
            'cpu': 'Core i7 9750H',
            'ram': '8GB',
            'hrdw': 'SSD 512GB',
            'vga': 'NVIDIA GTX 1660Ti',
            'screen': '15.6 FHD IPS 144Hz',
            "type": "new",
        },
        {
            'id': 'lap6',
            'name': 'Dell G3 3579 (Core i5-8300H, RAM 8GB, HDD 1TB + SSD 128GB , VGA 4GB NVIDIA GTX 1050Ti, 15.6 inch FHD IPS) Mới 100% ',
            'image': 'https://laptopaz.vn/media/product/1172_dell_inspiron_g7_7588_laptopaz__4_.JPG',
            'price': 18 * Math.pow(10, 6),
            'cpu': 'i5-8300H',
            'ram': '8GB',
            'hrdw': 'HHD 1TB +SSD 128Gb',
            'vga': 'GTX 1050Ti',
            'screen': '15.6 FHD IPS',
            "type": "new",
        },
        {
            'id': 'lap1',
            'name': 'Laptop Dell XPS 13-9343 (Core i5-5200U, RAM 4GB, SSD 128GB, VGA Intel HD Grapics 5500, 13.3 inch FHD IPS)',
            'image': 'https://laptopaz.vn/media/product/469_laptop_dell_xps_9343_i5_laptopaz__7_.JPG',
            'price': 12 * Math.pow(10, 6),
            'cpu': 'Core i5 - 5200U',
            'ram': '4GB',
            'hrdw': 'SSD 128GB',
            'vga': 'Intel HD Graphics 5500',
            'screen': '13.3 FHD IPS',
            "type": "old",
        },
        {
            'id': 'lap2',
            'name': 'Laptop Dell Precision 7510 (Core i7-6820HQ, RAM 8GB, SSD 256GB, VGA 2GB NVIDIA Quadro M1000M, 15.6 inch Full HD) ',
            'image': 'https://laptopaz.vn/media/product/1245_laptop_dell_precision_7510_laptopaz___7_.JPG',
            'price': 18 * Math.pow(10, 6),
            'cpu': 'Core i7 - 6820HQ',
            'ram': '8GB',
            'hrdw': 'SSD 256GB',
            'vga': 'NVIDIA Quadro M1000M 2GB',
            'screen': '15.6 FHD',
            "type": "old",
        },
        {
            'id': 'lap3',
            'name': 'Laptop HP EliteBook 840 G3 (Core i5-6200U, RAM 8GB, SSD 256GB, VGA Intel HD Graphics 520, 14 inch FHD) ',
            'image': 'https://laptopaz.vn/media/product/1144_laptop_hp_840_g3_laptopaz__11_.JPG',
            'price': 9 * Math.pow(10, 6),
            'cpu': 'i5 6200U',
            'ram': '8GB',
            'hrdw': 'SSD 256GB',
            'vga': 'Intel UHD Graphics 520',
            'screen': 'FHD',
            "type": "old",
        },
        {
            'id': 'lap4',
            'name': 'Laptop HP Zbook 15 G2 (Core i7-4810MQ, RAM 8GB, SSD 256GB, VGA 2GB NVIDIA K1100M, 15.6 inch FHD) ',
            'image': 'https://laptopaz.vn/media/product/1172_dell_inspiron_g7_7588_laptopaz__4_.JPG',
            'price': 11 * Math.pow(10, 6),
            'cpu': 'i7 4810MQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'K1100M',
            'screen': 'FHD TN',
            "type": "old",
        },
        {
            'id': 'lap5',
            'name': 'Laptop Dell Inspiron 5577 (Core i5-7300HQ, RAM 8GB, HDD 1TB + SSD 128GB, VGA 4GB NVIDIA GTX 1050, 15.6 inch FHD) Mới 98 >99%',
            'image': 'https://laptopaz.vn/media/product/1078_dell_5577__1_.jpg',
            'price': 15 * Math.pow(10, 6),
            'cpu': 'i5 7300HQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'NVIDIA GTX 960M',
            'screen': 'FHD TN',
            "type": "old",
        },
        {
            'id': 'lap1',
            'name': 'Laptop Dell Precision M4800 (Core i7-4800MQ, RAM 8GB, SSD 128GB + HDD 500GB, VGA 2GB NVIDIA Quadro K1100M, 15.6 inch FHD)',
            'image': 'https://laptopaz.vn/media/product/1037_laptop_dell_m4800_laptopaz__8_.JPG',
            'price': 12 * Math.pow(10, 6),
            'cpu': 'i7 4800MQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'K1100M',
            'screen': 'FHD TN',
            "type": "art",
        },
        {
            'id': 'lap2',
            'name': 'Laptop Dell Precision 7510 (Core i7-6920HQ, RAM 16GB, SSD 512GB, VGA 4GB NVIDIA Quadro M2000M, 15.6 inch FHD) ',
            'image': 'https://laptopaz.vn/media/product/1405_1285_laptop_dell_precision_7510_laptopaz___1_.jpg',
            'price': 17 * Math.pow(10, 6),
            'cpu': 'i5 6300HQ',
            'ram': '16GB',
            'hrdw': 'SSD 512GB',
            'vga': 'NVIDIA Quadro M2000M 4GB',
            'screen': '15.6 FHD',
            "type": "art",
        },
        {
            'id': 'lap3',
            'name': 'Laptop HP Zbook 15 G2 (Core i7-4810MQ, RAM 8GB, SSD 256GB, VGA 2GB NVIDIA K1100M, 15.6 inch FHD) ',
            'image': 'https://laptopaz.vn/media/product/1139_laptop_hp_zbook_g2_laptopaz__9_.JPG',
            'price': 11 * Math.pow(10, 6),
            'cpu': 'i7 4810MQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'K2100M',
            'screen': 'FHD TN',
            "type": "art",
        },
        {
            'id': 'lap4',
            'name': 'Laptop MSI GV62 (Core i5 8300H, RAM 8GB, HDD 1TB, VGA 4GB NVIDIA GTX 1050Ti, 15.6 inch FHD)',
            'image': 'https://laptopaz.vn/media/product/1412_1200_1183_laptop_gaming_msi_gv62_i7_laptopaz__3_.jpg',
            'price': 17 * Math.pow(10, 6),
            'cpu': 'Core i5 - 8300H',
            'ram': '8GB',
            'hrdw': 'HDD 1TB',
            'vga': 'NVIDIA GTX 1050Ti 4GB',
            'screen': '15.6 FHD ',
            "type": "art",
        },
        {
            'id': 'lap5',
            'name': 'Laptop MSI GF63-9RC-273VN Core i5 9th chính hãng full box mới 99% BH hãng 19 tháng ',
            'image': 'https://laptopaz.vn/media/product/1346_laptop_msi_gf63_9rc_laptopaz__3_.JPG',
            'price': 17 * Math.pow(10, 6),
            'cpu': 'Core i5 9300H',
            'ram': '8GB',
            'hrdw': 'SSD 256GB',
            'vga': 'NVIDIA GTX 1050 4GB',
            'screen': '15.6 FHD IPS',
            "type": "art",
        },
        {
            'id': 'lap1',
            'name': 'Dell Gaming7559 (Core i5-6300HQ, RAM 8GB, HDD 500GB + SSD 128GB, VGA 4GB GTX 960M, 15.6 inch FHD) Mới 98 >99%',
            'image': 'https://laptopaz.vn/media/product/849_laptop_dell_7559_laptopaz__7_.JPG',
            'price': 13 * Math.pow(10, 6),
            'cpu': 'i5 6300HQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'NVIDIA GTX 960M',
            'screen': 'FHD TN',
            'type': 'dell',
        },
        {
            'id': 'lap2',
            'name': 'Dell G7 7588 (Core i5-8300H, RAM 8GB, HDD 1TB + SSD 128GB , VGA 4GB NVIDIA GTX 1050Ti, 15.6 inch FHD IPS)',
            'image': 'https://laptopaz.vn/media/product/1172_dell_inspiron_g7_7588_laptopaz__4_.JPG',
            'price': 12 * Math.pow(10, 6),
            'cpu': 'Core i5 - 5200U',
            'ram': '8GB',
            'hrdw': 'SSD 128GB',
            'vga': 'Intel HD Graphics 5500',
            'screen': '13.3 FHD IPS ',
            'type': 'dell',
        },
        {
            'id': 'lap3',
            'name': 'Laptop Dell XPS 13-9343 (Core i5-5200U, RAM 4GB, SSD 128GB, VGA Intel HD Grapics 5500, 13.3 inch FHD IPS) ',
            'image': 'https://laptopaz.vn/media/product/469_laptop_dell_xps_9343_i5_laptopaz__7_.JPG',
            'price': 12 * Math.pow(10, 6),
            'cpu': 'Core i5 - 5200U',
            'ram': '8GB',
            'hrdw': 'SSD 128GB ',
            'vga': 'Intel HD Graphics 5500',
            'screen': '13.3 FHD IPS',
            'type': 'dell',
        },
        {
            'id': 'lap4',
            'name': 'Laptop Dell Precision 7510 (Core i7-6820HQ, RAM 8GB, SSD 256GB, VGA 2GB NVIDIA Quadro M1000M, 15.6 inch Full HD)',
            'image': 'https://laptopaz.vn/media/product/1245_laptop_dell_precision_7510_laptopaz___7_.JPG',
            'price': 18 * Math.pow(10, 6),
            'cpu': 'Core i7 - 6820HQ',
            'ram': '8GB',
            'hrdw': 'SSD 256GB',
            'vga': 'NVIDIA Quadro M1000M 2GB',
            'screen': '15.6 FHD',
            'type': 'dell',
        },
        {
            'id': 'lap5',
            'name': 'Laptop Dell Inspiron 5577 (Core i5-7300HQ, RAM 8GB, HDD 1TB + SSD 128GB, VGA 4GB NVIDIA GTX 1050, 15.6 inch FHD) Mới 98 >99%',
            'image': 'https://laptopaz.vn/media/product/1078_dell_5577__1_.jpg',
            'price': 15 * Math.pow(10, 6),
            'cpu': 'i5 7300HQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD1TB',
            'vga': 'GTX 1050',
            'screen': 'FHD TN',
            'type': 'dell',
        },
        {
            'id': 'lap1',
            'name': 'Asus FX504GD-E4571T (Core i5 8300H, RAM 8GB, SSHD 1TB, VGA 4GB NVIDIA GTX 1050, 15.6 inch FHD IPS)',
            'image': 'https://laptopaz.vn/media/product/1140_asus_fx504_laptopaz__2_.JPG',
            'price': 15 * Math.pow(10, 6),
            'cpu': 'Core i5 - 8300H',
            'ram': '8GB',
            'hrdw': 'SSHD 1TB',
            'vga': 'GTX 1050 4GB',
            'screen': '15.6 FHD IPS',
            'type': 'asus',
        },
        {
            'id': 'lap2',
            'name': 'Laptop Asus ROG Strix G531GT (Core i5-9300H, RAM 8GB, SSD 512GB , VGA 4GB NVIDIA GTX 1650, 15.6 inch FHD + IPS+120Hz)',
            'image': 'https://laptopaz.vn/media/product/1420_',
            'price': 21 * Math.pow(10, 6),
            'cpu': 'Core i5 - 9300H',
            'ram': '8GB',
            'hrdw': 'SSD 512GB',
            'vga': 'NVIDIA GTX 1650 4GB',
            'screen': '15.6 FHD IPS 120Hz',
            'type': 'asus',
        },
        {
            'id': 'lap3',
            'name': 'Laptop Asus ROG Strix Scar II GL504GM-ES044T (Core i7-8750H, RAM 16GB, SSD 128GB + HDD 1TB, VGA 6GB NVIDIA GTX 1060, 15.6 inch FHD 144Hz 3ms)',
            'image': 'https://laptopaz.vn/media/product/469_laptop_dell_xps_9343_i5_laptopaz__7_.JPG',
            'price': 28 * Math.pow(10, 6),
            'cpu': 'Core i7 - 8750H',
            'ram': '16GB',
            'hrdw': 'SSD 128GB + HDD 1TB',
            'vga': 'NVIDIA GTX1060 6GB',
            'screen': '15.6 FHD 144Hz 3ms',
            'type': 'asus',
        },
        {
            'id': 'lap4',
            'name': 'Asus FX505GE-BQ052T (Core i5 8300H, RAM 8GB, HDD 1TB, VGA 4GB NVIDIA GTX 1050Ti, 15.6 inch FHD IPS)',
            'image': 'https://laptopaz.vn/media/product/1360_fx505__4_.JPG',
            'price': 18 * Math.pow(10, 6),
            'cpu': 'Core i5 - 8300H',
            'ram': '8GB',
            'hrdw': 'HDD 1TB',
            'vga': 'GTX 1050Ti 4GB',
            'screen': '15.6 FHD IPS',
            'type': 'asus',
        },
        {
            'id': 'lap5',
            'name': 'Laptop Asus ROG Strix G531GT (Core i7-9750H, RAM 8GB, SSD 512GB , VGA 4GB NVIDIA GTX 1650, 15.6 inch FHD + IPS)',
            'image': 'https://laptopaz.vn/media/product/1359_',
            'price': 23 * Math.pow(10, 6),
            'cpu': 'Core i7 - 9750H',
            'ram': '8GB',
            'hrdw': 'SSD 512GB',
            'vga': 'NVIDIA GTX 1650',
            'screen': '15.6 FHD IPS',
            'type': 'asus',
        },
        {
            'id': 'lap1',
            'name': 'Laptop Acer Nitro 5 AN515-53-55G9 (Core i5-8300H, RAM 8GB, SSD 256GB, VGA 4GB NVIDIA GTX 1050Ti, 15.6 inch, FHD IPS)',
            'image': 'https://laptopaz.vn/media/product/1210_',
            'price': 17 * Math.pow(10, 6),
            'cpu': 'I5 8300H',
            'ram': '8GB',
            'hrdw': 'SSD 256',
            'vga': 'GTX 1050Ti',
            'screen': 'FHD TN',
            "type": 'acer',
        },
        {
            'id': 'lap2',
            'name': 'Laptop Acer VX5 591G (Core i5-7300HQ, RAM 8GB, HDD 1TB + SSD 128GB, VGA NVIDIA GTX 1050, 15.6 inch FHD)',
            'image': 'https://laptopaz.vn/media/product/1174_laptop_acer_vx5_laptopaz__7_.JPG',
            'price': 14 * Math.pow(10, 6),
            'cpu': 'i5 6300HQ',
            'ram': '8GB',
            'hrdw': 'SSD 128GB + HDD 500GB',
            'vga': 'NVIDIA GTX 960M',
            'screen': 'FHD TN',
            "type": 'acer',

        },
        {
            'id': 'lap3',
            'name': 'Acer Predator Helios 300 (Core i7-9750H, RAM 16GB,SSD 512GB, VGA 6GB NVIDIA GTX 1660Ti, 15.6 inch FHD IPS+144Hz) mới 100% nhập US',
            'image': 'https://laptopaz.vn/media/product/1363_acer_predator_helios_300__3_.JPG',
            'price': 33 * Math.pow(10, 6),
            'cpu': 'Core i7 9750H',
            'ram': '8GB',
            'hrdw': 'SSD 512GB',
            'vga': 'NVIDIA GTX 1660Ti',
            'screen': '15.6 FHD IPS 144Hz',
            "type": 'acer',
        },
        {
            'id': 'lap4',
            'name': 'Acer Predator Helios 300 (Core i7-9750H, RAM 16GB,SSD 512GB, VGA 6GB NVIDIA GTX 1660Ti, 15.6 inch FHD IPS+144Hz) mới 100% nhập US ',
            'image': 'https://laptopaz.vn/media/product/1363_acer_predator_helios_300__3_.JPG',
            'price': 33 * Math.pow(10, 6),
            'cpu': 'Core i7 9750H',
            'ram': '8GB',
            'hrdw': 'SSD 512GB',
            'vga': 'NVIDIA GTX 1660Ti',
            'screen': '15.6 FHD IPS 144Hz',
            "type": 'acer',
        },
        {
            'id': 'lap5',
            'name': 'Acer Predator Helios 300 (Core i7-9750H, RAM 8GB,SSD 256GB, VGA 6GB NVIDIA GTX 1660Ti, 15.6 inch FHD IPS+144Hz) mới 100% nhập US ',
            'image': 'https://laptopaz.vn/media/product/1172_dell_inspiron_g7_7588_laptopaz__4_.JPG',
            'price': 31 * Math.pow(10, 6),
            'cpu': 'Core i7 9750H',
            'ram': '8GB',
            'hrdw': 'SSD 256',
            'vga': 'NVIDIA GTX1660Ti 6GB',
            'screen': '15.6 FHD IPS 144Hz',
            "type": 'acer',
        }
    ]
